# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :update_localizables do
  	project_identifier = ""
  	api_token = ""
  	
  	destination = File.expand_path(File.dirname(File.dirname(__FILE__))) + "/../LokaliseTest/"
    puts "Downloading localizables on " + destination
    lokalise(
    	api_token: api_token,
    	project_identifier: project_identifier,
    	destination: destination
    )
  end
end
